server:
  port: 3000

spring:
  # ?????
  datasource:
    url: jdbc:mysql://localhost:3306/bangbang_store?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    # ????????????
    static-path-pattern: /public/**
  resources:
    static-locations: classpath:/public/
  profiles:
    active: cache
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  type-aliases-package: com.hjb.pojo #????
