server:
  port: 3000

spring:
  # ?????
  datasource:
    url: jdbc:mysql://localhost:3306/bangbang_store?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    # ????????????
    static-path-pattern: /public/**
  resources:
    static-locations: classpath:/public/

  profiles:
    active: cache,mq

  thymeleaf:
    cache: true  #开启缓存
    check-template: true  #检查模板是否存在
    check-template-location: true # 检查模板位置正确性 默认查找 resources templates文件夹内
    servlet:
      content-type: text/html # 直接嵌入到html文件中
    enabled: true
    encoding: UTF-8
  mail:
    # 指定邮件服务器地址
    host: smtp.qq.com
    # 登录账户
    username: 1181696482@qq.com
    # 登录密码
    password: yjnnbjqthqcjjahc
    # 端口
    port: 465
    # 默认编码
    default-encoding: UTF-8
    # 使用的协议
    protocol: smtps
    # 其他的属性
    properties:
      "mail.smtp.connectiontimeout": 5000
      "mail.smtp.timeout": 3000
      "mail.smtp.writetimeout": 5000
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  type-aliases-package: com.hjb.pojo #????

#OSS配置
aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: LTAI5tBW1EZYquNjKLAABZGd
      keysecret: Dr0mfcnsY3hS6emQF1WYACcZEIf0ug
      bucketname: bangbang-store

